# cartpole_common.yaml
# experiment_name: cartpole_logits_mlp

env: CartPole-v1
render: False
num_envs: 4

# network_type: mlp
# policy_type: logits
value_net_size: small
policy_net_size: small
clip_grad: 0

value_clip: 0.1
policy_clip: 0.2
value_lr: 0.001
policy_lr: 0.0003
gamma: 0.99
gae_lambda: 0.97
max_KL: 0.005
entropy_coef: 0.0

temp_scheduler_kwargs:
  start_temp: 2.0
  min_temp: 0.05
  max_temp: 2.0
  decay_type: 'exponential'
  l_num_steps: 150
  e_decay_rate: 0.97
  accept_threshold: 400
  slope_threshold: 0.01
  window_size: 20
  plateau_boost: 1.2
  suppress_factor: 0.85
  frozen: true

batch_size: 1024
max_epochs: 4
num_episodes: 150
max_episode_length: 500
rollout_length: 4096