# cartpole_common.yaml
seed: 0

env: CartPole-v1
render: False
num_envs: 16

quantize: False

log_frequency: 3

# network_type: mlp
# policy_type: logits
value_net_size: small
policy_net_size: small
clip_grad: 0

value_clip: 0.1
policy_clip: 0.1
value_lr: 0.001
policy_lr: 0.0003
gamma: 0.99
gae_lambda: 0.97
max_KL: 0.0
entropy_coef: 0.0

batch_size: 1024
max_epochs: 4
num_episodes: 150
max_episode_length: 500
rollout_length: 4096

save_frames: False
log_early_phase: 0