# cartpole_GNN_noise_entropy.yaml
experiment_name: cartpole_GNN_noise_entropy_mlp

network_type: mlp
policy_type: GNN

entropy_coef: 0.005

intervals:
  fn_name: trivial
  kwargs:
    xmin: -1
    xmax: 1
    action_space_size: 2

mapping:
  fn_name: trivial
  kwargs:
    action_space_size: 2

noise_scheduler_kwargs:
  num_steps: 150
  start_std: 0.3
  min_std: 0.002
  max_std: 0.4
  frozen: False