# cartpole_logits_noise.yaml
experiment_name: cartpole_logits_noise_mlp

network_type: mlp
policy_type: logits

noise_scheduler_kwargs:
  num_steps: 150
  start_std: 0.3
  min_std: 0.002
  max_std: 0.4
  frozen: False