# cartpole_GNN_K_frozen.yaml
experiment_name: cartpole_GNN_K_frozen_mlp

K_num_components: 3

network_type: mlp
policy_type: GNN_K

intervals:
  fn_name: trivial
  kwargs:
    xmin: -1
    xmax: 1
    action_space_size: 2

mapping:
  fn_name: trivial
  kwargs:
    action_space_size: 2

temp_scheduler_kwargs:
  start_temp: 1.0
  min_temp: 0.05
  max_temp: 2.0
  decay_type: 'exponential'
  l_num_steps: 150
  e_decay_rate: 0.97
  accept_threshold: 400
  slope_threshold: 0.01
  window_size: 20
  plateau_boost: 1.2
  suppress_factor: 0.85
  frozen: true