# cartpole_CMU_entropy.yaml
experiment_name: cartpole_CMU_entropy_mlp

network_type: mlp
policy_type: CMU

noise_coeff: 1

entropy_coef: 0.005

aux_loss_kwargs:
  a: 1
  b: 1
  M: 1
  aux_coeff: 0.01
  aux_mix: 0.9