# cartpole_CMU_entropy.yaml
experiment_name: cartpole_CMU_entropy_mlp

network_type: mlp
policy_type: CMU

confidence_hidden_multiplier: 2

entropy_coef: 0.005

aux_loss_kwargs:
  a: 1
  b: 1
  M: 1
  aux_strength: 0.02
  aux_coeffs:
    alignment: 0
    penalty: 0
    margin: 0