# pong_CMU_.yaml
experiment_name: pong_CMU_entropy_cnn

network_type: cnn
policy_type: CMU

noise_coeff: 0.05

aux_loss_kwargs:
  a: 0.1
  b: 0.1
  M: 1
  aux_coeff: 0.02
  aux_mix: 0.5
  
entropy_coef: 0.01