# pong_ablation_penalty_margin.yaml
experiment_name: pong_ablation_penalty_margin_cnn

confidence_hidden_multiplier: 2

aux_loss_kwargs:
  a: 1
  b: 1
  M: 1
  aux_strength: 0.02
  aux_coeffs:
    alignment: 0
    penalty: 5
    margin: 1
