# pendulum_CMU_entropy.yaml
experiment_name: pendulum_CMU_entropy_mlp

network_type: mlp
policy_type: CMU

entropy_coef: 0.005

confidence_hidden_multiplier: 2

aux_loss_kwargs:
  a: 1
  b: 1
  M: 1
  aux_coeff: 0
  aux_mix: 1.0
