# pendulum_GNN_K_entropy.yaml
experiment_name: pendulum_GNN_K_entropy_mlp

network_type: mlp
policy_type: GNN_K

K_num_components: 5

entropy_coef: 0.005

intervals:
  fn_name: trivial
  kwargs:
    xmin: -1
    xmax: 1
    action_space_size: 21

mapping:
  fn_name: trivial
  kwargs:
    action_space_size: 21