# pendulum_GNN_N_entropy.yaml
experiment_name: pendulum_GNN_N_entropy_mlp

network_type: mlp
policy_type: GNN_N

entropy_coef: 0.005

noise_coeff: 1

aux_loss_kwargs:
  a: 1
  b: 1
  M: 1
  aux_coeff: 0.01
  aux_mix: 0.5

save_frames: True