# pendulum_logits_noise.yaml
experiment_name: pendulum_logits_noise_mlp

network_type: mlp
policy_type: logits

noise_scheduler_kwargs:
  num_steps: 500
  start_std: 0.1
  min_std: 0.001
  max_std: 0.2
  frozen: False