# pendulum_GNN_K_.yaml
experiment_name: pendulum_GNN_K_mlp

network_type: mlp
policy_type: GNN_K

K_num_components: 3

intervals:
  fn_name: trivial
  kwargs:
    xmin: -1
    xmax: 1
    action_space_size: 7

mapping:
  fn_name: trivial
  kwargs:
    action_space_size: 7