# pendulum_common.yaml

env: Pendulum-v1
render: False
num_envs: 24

quantize: True
num_bins: 7

log_frequency: 5

# network_type: mlp
# policy_type: logits
value_net_size: small
policy_net_size: small
clip_grad: 0

value_clip: 0.1
policy_clip: 0.2
value_lr: 0.001
policy_lr: 0.0003
gamma: 0.99
gae_lambda: 0.97
max_KL: 0.005
entropy_coef: 0.0

batch_size: 512
max_epochs: 4
num_episodes: 500
max_episode_length: 200
rollout_length: 4096