# pendulum_GNN_K_noise.yaml
experiment_name: pendulum_GNN_K_noise_mlp

network_type: mlp
policy_type: GNN_K

K_num_components: 3

intervals:
  fn_name: trivial
  kwargs:
    xmin: -1
    xmax: 1
    action_space_size: 7

mapping:
  fn_name: trivial
  kwargs:
    action_space_size: 7

noise_scheduler_kwargs:
  num_steps: 500
  start_std: 0.1
  min_std: 0.001
  max_std: 0.2
  frozen: False