# pendulum_GNN_N_entropy.yaml
experiment_name: pendulum_GNN_N_entropy_mlp

network_type: mlp
policy_type: GNN_N

noise_coeff: 0.05

entropy_coef: 0.005

aux_loss_kwargs:
  a: 0.1
  b: 0.1
  M: 1
  aux_coeff: 0.02
  aux_mix: 0.5
