# breakout_GNN_N_.yaml
experiment_name: breakout_GNN_N_entropy_cnn

network_type: cnn
policy_type: GNN_N

aux_loss_kwargs:
  a: 0.1
  b: 0.1
  M: 1
  aux_coeff: 0.02
  aux_mix: 0.5

entropy_coef: 0.005