# acrobot_common.yaml
seed: 0

env: Acrobot-v1
render: False
num_envs: 8

quantize: False

log_frequency: 3

network_type: mlp
policy_type: CMU
value_net_size: small
policy_net_size: small
clip_grad: 0
confidence_hidden_multiplier: 2

value_clip: 0.1
policy_clip: 0.2
value_lr: 0.001
policy_lr: 0.0003
gamma: 0.99
gae_lambda: 0.97
max_KL: 0.000
entropy_coef: 0.01

batch_size: 256
max_epochs: 4
num_episodes: 300
max_episode_length: 500
rollout_length: 2048

save_frames: False
log_early_phase: 0